name: Deploy to Gitee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: |
          cd .vitepress/dist
          git init
          git config user.email "yyx990803@gmail.com"
          git config user.name "Evan You"
          git add .
          git commit -m "update docs"
          git remote add origin https://yyx990803:${{ secrets.GITEE_TOKEN }}@gitee.com/vuejs-cn/vite-docs-cn.git
          git push origin HEAD:master --force